export function RH1(req, res, next) {
    console.log("loading data")
    console.log("Successsfully got all the data")
    res.send("Successsfully got all the data")  
}

export function RH2(req, res, next) {
    console.log("loading data")
    console.log("Successsfully send all the require data to user")
    res.send("Successsfully send all the require data user")
}

export function errHandler(err, req, res, next){
    if(err){
        console.log("This error is generated by errHandler function")
        res.status(401).send("Unauthorized login")
    }
}